version: "{build}"

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4.1"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install

test_script:
  - .\test\test-files\foundry-release-echo\foundry-release-echo
  - .\test\test-files\foundry-release-echo\foundry-release-echo --help
  - .\test\test-files\foundry-release-echo\foundry-release-echo --spec-version
  - npm run test-windows-ci

build: off
